kind: project
metadata:
  name: git-test-shapira
spec:
  functions:
  - url: add_2.py
    name: add_2
    kind: job
    image: mlrun/mlrun
    handler: add_2
  - url: multi_2.py
    name: multi_2
    kind: job
    image: mlrun/mlrun
    handler: multi_2
  - url: multi_4.py
    name: multi_4
    kind: job
    image: mlrun/mlrun
    handler: multi_4
  workflows: []
  artifacts: []
  source: ''
  desired_state: online
